[project]
authors = ["Sylens Wong <qiumin14@163.com>"]
channels = ["conda-forge"]
description = "Dependency for ReviewGPT"
name = "ReviewGPT"
platforms = ["linux-aarch64", "linux-64"]
version = "0.1.1"

[tasks]

[dependencies]
python = "*"
gradio = "*"
pandas = "*"
openai = "0.27.*"
pdfplumber = "*"
biopython = "*"
tiktoken = "*"
nicegui = ">=2.0"

[pypi-dependencies]
rispy = "*"
